apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloggingapplication-deployment
spec:
  selector:
    matchLabels:
      app: bloggingapplication
  replicas: 2
  template:
    metadata:
      labels:
        app: bloggingapplication
    spec:
      containers:
        - name: bloggingapplication
          image: ngozin/blogging-application:latest # Updated image to private DockerHub image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred # Reference to the Docker registry secret
---
apiVersion: v1
kind: Service
metadata:
  name: bloggingapplication-ssvc
spec:
  selector:
    app: bloggingapplication
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer
